### ISSUE TITLE
Unable to see tile outline while drawing new tile with module enabled

### ISSUE THREAD

**Issue by Vauryx** [Haxxer/FoundryVTT-TileMask#1]
The tile outline that lets you see where you are drawing a new tile becomes invisible with the module enabled

https://user-images.githubusercontent.com/32877348/129946479-bf7208b9-fca5-4411-b818-94608b7c36a5.mp4

**Comment by Vauryx** [comment]
should have attached this to the initial issue sorry! These are the errors in the console when a tile is drawn
![image](https://user-images.githubusercontent.com/32877348/129957611-7717f6cb-eec0-462e-b65f-04fea2ae2115.png)

**Comment by Haxxer** [comment]
Fixed in 1.1.0
